# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 14516f60d968b6edc3fd445d7d62da0ea948c91b4080ba6ff346193502354fe136fbf83baac80cc33b3a951ac00c2a24d945e97c8b3162a8761cc30ae420071e

test:
  secret_key_base: 727ec5e090a1c606fc2266d6e72e6dd0411adda9508f2f68ec8ccde4cafac0a1d2109511d9df5743b73ac5f4d5bb132546fce2c3a0b5386e5018824444398c12

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
